name = "Eip20"
version = "0.1.0"
defaultTargets = ["Eip20"]

[[require]]
scope = "leanprover-community"
name = "mathlib"
rev = "v4.29.1"

[[lean_lib]]
name = "Eip20"
srcDir = "."
leanOptions = [{ name = "autoImplicit", value = false }]

[[lean_lib]]
name = "EIP20V2"
srcDir = "."
leanOptions = [{ name = "autoImplicit", value = false }]
