name = "Sequences"
version = "0.1.0"
defaultTargets = ["SequencesV2"]

[[require]]
scope = "leanprover-community"
name = "mathlib"
rev = "v4.29.1"

[[lean_lib]]
name = "Sequences"
srcDir = "."
leanOptions = [{ name = "autoImplicit", value = false }]

[[lean_lib]]
name = "SequencesV2"
srcDir = "."
leanOptions = [{ name = "autoImplicit", value = false }]
